title: "Mike Enting"
description: "Personal website and professional profile"
baseurl: "" 
url: "https://mikeenting.me" 
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - index.md
  - resume.md
  - contact.md